### ISSUE TITLE
Coverage CI failing

### ISSUE THREAD

**Issue by m-albert** [m-albert/fractal-ome-zarr-hcs-stitching#17]
Opening an issue to track this CI failure. Encountered and mentioned by @jluethi [here](https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/pull/14#issuecomment-2252611602).

**Comment by m-albert** [comment]
I was confused, this has been taken care of by https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/pull/15.

**Comment by jluethi** [comment]
Hmm, #15 doesn't fully solve the CI issue unfortunately.

It got it mostly working in the branch. I never had actual comments being automated to the PR, but at least it was calculating coverage and making it accessible in the action.

Unfortunately, it looks like something broke again in the coverage comment approach now that it's merged into main. I guess we can just turn the whole coverage block off in the CI for the moment and get back to it later if we want to actively track it

**Comment by m-albert** [comment]
Just quickly commenting that the PR commenting seems to have worked [here](https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/pull/19#issuecomment-2286802909).

**Comment by jluethi** [comment]
> Just quickly commenting that the PR commenting seems to have worked https://github.com/m-albert/fractal-ome-zarr-hcs-stitching/pull/19#issuecomment-2286802909.

@m-albert Yes, was also surprised by that! 😅 I'll give it another shot later this week to see if I can correctly configure it to not try that on main. Otherwise, let's turn it off

**Comment by jluethi** [comment]
Now appears to be solved, also works in main :)
