### ISSUE TITLE
Run Zenodo integration tests with GitHub CI

### ISSUE THREAD

**Issue by nrepina** [m-albert/fractal-ome-zarr-hcs-stitching#4]
Set up Github action for testing & data download from Zenodo via pooch + caching

**Comment by nrepina** [comment]
@jluethi @m-albert  

Test datasets are now on Zenodo and ready to be added as integration tests!

See links below. 

SearchFirst (ome-zarr): https://zenodo.org/records/12795788
Tiled (ome-zarr, with sparse fields): https://zenodo.org/records/12795605

If we need to re-generate the zarrs or test on tifs, the raw tifs used for input are also now publicly available:
SearchFirst (tif): https://zenodo.org/records/12795729
Tiled (tif): https://zenodo.org/records/12794819

**Comment by m-albert** [comment]
This is awesome @nrepina !
