### ISSUE TITLE
Pyramid building issue

### ISSUE THREAD

**Issue by nrepina** [m-albert/fractal-ome-zarr-hcs-stitching#8]
Look into pyramid building issue

**Comment by jluethi** [comment]
I don't fully understand this rechunking issue during pyramid building. Something goes wrong with irregular chunk sizes if we use the default approach. The build_pyramid API allows to specify chunk_sizes and specifying the original chunk size (which makes sense to me) avoids this issue.

This will be added by #1 now and I can't reproduce the issue in that setting anymore
